name: admin_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  videosdk: ^1.1.6
  http: ^1.0.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.2
  touch_ripple_effect: ^2.2.3
  flutter_vlc_player: ^7.2.0
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  timeago: ^3.5.0
  json_annotation: ^4.8.1
  chat_bubbles: ^1.5.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env